### ISSUE TITLE
License, contributing etc

### ISSUE THREAD

**Issue by harcel** [BilHim/trafficSimulator#1]
Hi! 
Looks like a great repository! I really enjoyed the article on Medium. In order for people to understand where they can take this, it would be helpful to have some extra files in the repo. Most importantly, a license. Without any license, people should assume that the source code cannot be used for anything, while your article suggests that you wouldn't mind other people playing with it. A simple, very permissive license would be the MIT license, but others are explained [here](https://www.whitesourcesoftware.com/resources/blog/open-source-licenses-explained/).
Futhermore, people would like to know how to contribute, so a CONTRIBUTE.md would be a welcome addition. Codes of conduct get useful when more than a few people who know each other well start contributing. Github offers much of these (standard versions that you can adapt, but please don't adapt the wording of the standard licenses!) that can easily be added to your repo, see this [explanation page](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions). I'd be happy to help, but for now, it is your (closed source) repo!

**Comment by BilHim** [comment]
Hi, the project is now licensed under MIT. I also added a README file and a CONTRIBUTING file.
Thanks for pointing this out. Forgetting a LICENSE file and a README file is a very bad practice.
I didn't think people were actually going to be interested in the project when I went to bed yesterday.
