### ISSUE TITLE
Need to solve import structure problem

### ISSUE THREAD

**Issue by LemonCANDY42** [BilHim/trafficSimulator#10]
Example files in different directories need to be re-pasted when running, which is very annoying.

**Comment by LemonCANDY42** [comment]
I would like to contribute to this project
please add me to the list.

**Comment by LemonCANDY42** [comment]
@BilHim

**Comment by robertoalexisnHN** [comment]
hola me puedes ayudar

**Comment by BilHim** [comment]
One way to solve this is stated in [13#issuecomment-1487945031](https://github.com/BilHim/trafficSimulator/issues/13#issuecomment-1487945031).

The solution is currently in progress #14.
