### ISSUE TITLE
No module named 'trafficSimulator'

### ISSUE THREAD

**Issue by SiYeon-Kwon** [BilHim/trafficSimulator#13]
I download and use your git.
All files in trafficSimulator are compileable, but the module 'from trafficSimulator import *' cannot be read from example and test.
Is there any process that I need to be done?

**Comment by BilHim** [comment]
The `trafficSimulator` folder should be copied to the current working directory to be used as a module.
Here is an example of how a project using this module may be structured:
```
.
└── Project Folder/
    ├── trafficSimulator/
    │   └── ...
    ├── example1.py
    ├── example2.py
    └── ...
```
The file `example1.py` can now access the module using `import trafficSimulator as ts` for example.

The solution to this would be to publish the module as a PyPI package that can be installed using `pip` and used directly.
I will add this as a todo.

**Comment by BilHim** [comment]
The solution is currently in progress #14.
