### ISSUE TITLE
Latest changes not in GitHub?

### ISSUE THREAD

**Issue by artmen1516** [BilHim/trafficSimulator#17]
Hello, nice work with this repo,
I read your article and wanted to give it a try,
but when I cloned it I noticed that there is a lot missing,
in the article you mention a Road class, TrafficSignal, and other important things for the simulation...
would it be possible to have these latest changes in your repo to test the full functionality of it?

Thanks in advance.

**Comment by BilHim** [comment]
The current repo is actually ahead of the code in the article.
I have rewritten the code using a slightly different approach in the current main branch and it is still under development.

You can check out the old code (the same as the one in the article) in this commit https://github.com/BilHim/trafficSimulator/commit/9f073f603180534973a376dcd4157eae282339d8.

You can clone it using 
```
git clone https://github.com/BilHim/trafficSimulator.git
cd trafficSimulator
git reset --hard 9f073f603180534973a376dcd4157eae282339d8
```

Let me know if that helps.

**Comment by artmen1516** [comment]
oh okay, as I saw less files and classes than the article I thought main was outdated, 
thanks for the information. 
and actually the commit  9f073f6 didn't work, but the previous one to that did work 43b06d6

`git reset --hard 43b06d6`

thanks!

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/60411196/231261021-04a73e24-94e8-4b6e-b7f9-0cc171b96e8e.png">
