### ISSUE TITLE
Get in touch

### ISSUE THREAD

**Issue by rampallishyam** [BilHim/trafficSimulator#3]
Hi Bilal,

First of all, Great to see such a repo!. 

While I've downloaded the repo and started using it, I felt many more features can be used to improve it. Why would I want to do this? For me, I am interested to make traffic simulation open-source. There exist many tools but the tool itself cannot be customizable to a higher extent. But with your implementation, I am sure it can be extended to a level that can be used by many people. Especially, students like you. Please get back to this e-mail and I hope we can get in touch. I await more interesting things with this implementation in future.

e-mail: rampallishyam2@gmail.com 
Best regards,
Shyam.

**Comment by paul-data-ai** [comment]
Hi Bilal,

I have downloaded and started explored the repo.
It has a lot of applications especially in the industry of public transportation that I'm currently engaged in.

I wouldn't consider myself an expert user of python, but I'll say I do have a thing or two to contribute to this project.
Currently, I'm thinking of modeling the traffic flow of a city such as Lagos  (the second-largest city in Africa) and attempt a solution for its traffic issues.

Thanks for this headstart, Bilal!

**Comment by rinosimeone** [comment]
I think it could be very interesting and somewhat inovative to consider the possibility to add Smart / Cooperative data generated by the vehicles on the basis of thr ETSI standards (https://www.car-2-car.org/about-c-its/ and https://ec.europa.eu/transport/themes/its/road/action_plan/cooperative_systems_it).
Vehicle should generate messages of statuses and warnings to be exchanged among them.
Of course I would also consider aside vechicles the so called vulnerable users.
Maybe I can contribute on this ?
